/**
 * author : Loic France
 * created 05/31/2016
 */
'use strict';Game.board={};
Game.board.Map=function(){var r=Game.Map,a=function(b,c,f,a,g){r.call(this,b,c,f);this.horizontalCases=a;this.verticalCases=g;this.boardMarginRight=this.boardMarginBottom=this.boardMarginLeft=this.boardMarginTop=0};classExtend(r,a);a.prototype.getHorizontalCases=function(){return this.horizontalCases};a.prototype.getVerticalCases=function(){return this.verticalCases};a.prototype.setHorizontalCases=function(b){this.horizontalCases=b};a.prototype.setVerticalCases=function(b){this.verticalCases=b};a.prototype.getBoardMarginLeft=
function(){return this.boardMarginLeft};a.prototype.getBoardMarginTop=function(){return this.boardMarginTop};a.prototype.getBoardMarginRight=function(){return this.boardMarginRight};a.prototype.getBoardMarginBottom=function(){return this.boardMarginBottom};a.prototype.setBoardMarginLeft=function(b){this.boardMarginLeft=b};a.prototype.setBoardMarginTop=function(b){this.boardMarginTop=b};a.prototype.setBoardMarginRight=function(b){this.boardMarginRight=b};a.prototype.setBoardMarginBottom=function(b){this.boardMarginBottom=
b};a.prototype.getBoardRect=function(){return this.getGameRect().clone().addMargins(-this.getBoardMarginLeft(),-this.getBoardMarginTop(),-this.getBoardMarginRight(),-this.getBoardMarginBottom())};a.prototype.getCaseWidth=function(b){return b.width()/this.getHorizontalCases()};a.prototype.getCaseHeight=function(b){return b.height()/this.getVerticalCases()};a.prototype.getCasePosition=function(b,c,f){var a=this.getCaseWidth(b),g=this.getCaseHeight(b);return new Vec2(b.left+a*(c+.5),b.top+g*(f+.5))};
a.prototype.getCaseXY=function(b,c){var f=this.getCaseWidth(b),a=this.getCaseHeight(b);return new Vec2(Math.floor((c.x-b.left)/f),Math.floor((c.y-b.top)/a))};a.prototype.getCaseShape=function(b,c,f){return this.getCaseRect(b,c,f).getShape()};a.prototype.getCaseRect=function(b,c,f){var a=this.getCaseWidth(b),g=this.getCaseHeight(b);c=b.left+a*c;b=b.top+g*f;return new Rect(c,b,c+a,b+g)};a.prototype.renderDebug=function(b){var c=this.getBoardRect();b.strokeStyle="#F00";c.draw(b,!1,!0);var f=this.getHorizontalCases(),
a=this.getCaseWidth(c),g=this.getCaseHeight(c),d=c.left,e=c.top;b.beginPath();for(c.pushPath(b);0<--f;)d+=a,b.moveTo(d,c.top),b.lineTo(d,c.bottom);for(f=this.getVerticalCases();0<f--;)e+=g,b.moveTo(c.left,e),b.lineTo(c.right,e);b.closePath();b.stroke()};var t=override(a,"showMouseOverInfos",function(b,c,f){t.call(this,b,c,f);if(this.debug){var a=this.getPointerPosition(),g=this.getBoardRect();if(g.contains(a)){f.strokeStyle="#00F";f.lineWidth*=2;var d=this.getCaseXY(g,a);f.beginPath();this.getCaseShape(g,
d.x,d.y).pushPath(f);(new Line(this.getCasePosition(g,d.x,d.y),a)).pushPath(f);f.closePath();f.stroke();f.lineWidth/=2;c=this.getObjectsAtCase(g,c,d.x,d.y);c.length&&c[0].renderMouseOver(f,a,b,this.debug)}}});a.boardObjectFilter=function(b){return b.addOccupationToMap};a.prototype.getBoardObjects=function(b){return b.getObjects(a.boardObjectFilter)};a.prototype.getObjectsAtCase=function(b,c,f,a){b=c.length;for(var g,d,e,m,h,l=[];b--;)if(g=c[b],m=g.boardOccupationMatrix)d=g.getCaseX(),e=g.getCaseY(),
h=m.length,e=Math.floor(h/2)+a-e,0<=e&&e<h&&(h=m[e].length,d=Math.floor(h/2)+f-d,0<=d&&d<h&&+m[e][d]&&l.push(g));return l};a.prototype.getNativeOccupationMap=function(){for(var b=this.getVerticalCases(),c=this.getHorizontalCases(),f=Array(b),a;b--;)for(f[b]=Array(c),a=c;a--;)f[b][a]=0;return f};a.prototype.getOccupationMap=function(b){for(var c=this.getNativeOccupationMap(),f=b.length;f--;)b[f].addOccupationToMap(c);return c};a.prototype.getDistanceMap=function(b,c,f){var a=b.length,g=b[0].length,
d,e,m=f,h=f,l=c,p=c,q=!1,k=Array(a);for(d=0;d<a;d++)for(k[d]=Array(g),e=0;e<g;e++)k[d][e]=-1;for(k[f][c]=0;!q;)for(q=!0,d=m;d<=h;d++)for(e=l;e<=p;e++)0<=k[d][e]&&(c=k[d][e]+1,0<d&&(-1==k[d-1][e]||k[d-1][e]>c)&&!b[d-1][e]&&(k[d-1][e]=c,d==m&&m--,q=!1),d<a-1&&-1==k[d+1][e]&&!b[d+1][e]&&(k[d+1][e]=c,d==h&&h++,q=!1),0<e&&-1==k[d][e-1]&&!b[d][e-1]&&(k[d][e-1]=c,e==l&&l--,q=!1),e<g-1&&-1==k[d][e+1]&&!b[d][e+1]&&(k[d][e+1]=c,e==p&&p++,q=!1));return k};a.prototype.getPath=function(b,c,a,n,g){var d=[],e,m=
c,h=a,l=b[0].length,p=b.length,q=new Vec2(n,g),k=Vec2.squareDistance(new Vec2(c,a),q);n=function(c,a){e=b[a][c];m=c;h=a;k=Vec2.squareDistance(new Vec2(c,a),q)};for(g=function(c,a){return b[a][c]<e||b[a][c]==e&&Vec2.squareDistance(new Vec2(c,a),q)<k};b[a][c];)if(e=-1==b[a][c]?Number.MAX_SAFE_INTEGER:b[a][c],0<c&&-1!=b[a][c-1]&&g(c-1,a)&&n(c-1,a),c<l-1&&-1!=b[a][c+1]&&g(c+1,a)&&n(c+1,a),0<a&&-1!=b[a-1][c]&&g(c,a-1)&&n(c,a-1),a<p-1&&-1!=b[a+1][c]&&g(c,a+1)&&n(c,a+1),m!=c||h!=a)c=m,a=h,d.push(c,a);else break;
return d};a.prototype.findPath=function(a,c,f,n,g){return this.getPath(this.getDistanceMap(this.getOccupationMap(this.getBoardObjects(a)),n,g),c,f,n,g)};return a}();Game.board.Object=function(){var r=Game.objects.Object.Static,a=function(c,a,b){r.call(this,c.getCasePosition(c.getBoardRect(),a,b));this.caseX=a;this.caseY=b};classExtend(r,a);a.prototype.boardMoveSpeed=100;var t=override(a,"moveOnFrame",function(c,a){t.call(this,c,a);if(this.target){var b=Vec2.translation(this.getPosition(),this.target);if(b.isZero())this.target=null;else if(b.clampMagnitude(0,this.boardMoveSpeed*a),this.move(b),c=c.getMap(),c=c.getCaseXY(c.getBoardRect(),this.getPosition()),c.x!=
this.getCaseX()||c.y!=this.getCaseY())this.setCaseX(c.x),this.setCaseY(c.y)}});a.prototype.getCaseX=function(){return this.caseX};a.prototype.getCaseY=function(){return this.caseY};a.prototype.setCaseX=function(a){this.caseX=a;return this};a.prototype.setCaseY=function(a){this.caseY=a;return this};a.prototype.setBoardMoveSpeed=function(a){this.boardMoveSpeed=a;return this};a.prototype.getBoardMoveSpeed=function(){return this.boardMoveSpeed};a.prototype.moveToCase=function(a,b,n){this.target=a.getCasePosition(a.getBoardRect(),
b,n);return this};a.prototype.skipMovement=function(){this.target&&this.move(Vec2.translation(this.getPosition(),this.target));return this};a.prototype.isMovementFinished=function(){return!this.target};a.prototype.boardOccupationMatrix=["1"];a.prototype.addOccupationToMap=function(a){for(var b=a.length,n,g=this.boardOccupationMatrix,d=g.length,e,m=this.getCaseY()-Math.floor(d/2),h,l=0;l<d&&l+m<b;l++){n=a[l].length;e=g[l].length;h=this.getCaseX()-Math.floor(e/2);for(var p=0;p<e&&p+h<n;p++)a[l+m][p+
h]|=parseInt(g[l][p])}};a.prototype.collisionLayers=[Game.objects.Object.NO_COLLISION_LAYER];var b=override(a,"getInformations",function(){var a=b.call(this);a.push(["x: ",this.getCaseX().toString(),", y: ",this.getCaseY().toString()].join(""));return a});return a}();
