Game.board={};
Game.board.Map=function(){var r=Game.Map,a=function(b,c,f,g,a){r.call(this,b,c,f);this.horizontalCases=g;this.verticalCases=a;this.boardMarginRight=this.boardMarginBottom=this.boardMarginLeft=this.boardMarginTop=0};classExtend(r,a);a.prototype.getHorizontalCases=function(){return this.horizontalCases};a.prototype.getVerticalCases=function(){return this.verticalCases};a.prototype.setHorizontalCases=function(b){this.horizontalCases=b};a.prototype.setVerticalCases=function(b){this.verticalCases=b};a.prototype.getBoardMarginLeft=
function(){return this.boardMarginLeft};a.prototype.getBoardMarginTop=function(){return this.boardMarginTop};a.prototype.getBoardMarginRight=function(){return this.boardMarginRight};a.prototype.getBoardMarginBottom=function(){return this.boardMarginBottom};a.prototype.setBoardMarginLeft=function(b){this.boardMarginLeft=b};a.prototype.setBoardMarginTop=function(b){this.boardMarginTop=b};a.prototype.setBoardMarginRight=function(b){this.boardMarginRight=b};a.prototype.setBoardMarginBottom=function(b){this.boardMarginBottom=
b};a.prototype.getBoardRect=function(){return this.getGameRect().clone().addMargins(-this.getBoardMarginLeft(),-this.getBoardMarginTop(),-this.getBoardMarginRight(),-this.getBoardMarginBottom())};a.prototype.getCaseWidth=function(b){return b.width()/this.getHorizontalCases()};a.prototype.getCaseHeight=function(b){return b.height()/this.getVerticalCases()};a.prototype.getCasePosition=function(b,c,f){var g=this.getCaseWidth(b),a=this.getCaseHeight(b);return new Vec2(b.left+g*(c+.5),b.top+a*(f+.5))};
a.prototype.getCaseXY=function(b,c){var f=this.getCaseWidth(b),g=this.getCaseHeight(b);return new Vec2(Math.floor((c.x-b.left)/f),Math.floor((c.y-b.top)/g))};a.prototype.getCaseShape=function(b,c,f){return this.getCaseRect(b,c,f).getShape()};a.prototype.getCaseRect=function(b,c,f){var g=this.getCaseWidth(b),a=this.getCaseHeight(b);c=b.left+g*c;b=b.top+a*f;return new Rect(c,b,c+g,b+a)};a.prototype.renderDebug=function(b){var c=this.getBoardRect();b.strokeStyle="#F00";c.draw(b,!1,!0);var f=this.getHorizontalCases(),
a=this.getCaseWidth(c),h=this.getCaseHeight(c),d=c.left,e=c.top;b.beginPath();for(c.pushPath(b);0<--f;)d+=a,b.moveTo(d,c.top),b.lineTo(d,c.bottom);for(f=this.getVerticalCases();0<f--;)e+=h,b.moveTo(c.left,e),b.lineTo(c.right,e);b.closePath();b.stroke()};var t=override(a,"showMouseOverInfos",function(b,c,f){t.call(this,b,c,f);if(this.debug){var a=this.getPointerPosition(),h=this.getBoardRect();if(h.contains(a)){f.strokeStyle="#00F";f.lineWidth*=2;var d=this.getCaseXY(h,a);f.beginPath();this.getCaseShape(h,
d.x,d.y).pushPath(f);(new Line(this.getCasePosition(h,d.x,d.y),a)).pushPath(f);f.closePath();f.stroke();f.lineWidth/=2;c=this.getObjectsAtCase(h,c,d.x,d.y);c.length&&c[0].renderMouseOver(f,a,b,this.debug)}}});a.boardObjectFilter=function(b){return b.addOccupationToMap};a.prototype.getBoardObjects=function(b){return b.getObjects(a.boardObjectFilter)};a.prototype.getObjectsAtCase=function(b,c,f,a){b=c.length;for(var h,d,e,n,k,m=[];b--;)if(h=c[b],n=h.boardOccupationMatrix)d=h.getCaseX(),e=h.getCaseY(),
k=n.length,e=Math.floor(k/2)+a-e,0<=e&&e<k&&(k=n[e].length,d=Math.floor(k/2)+f-d,0<=d&&d<k&&+n[e][d]&&m.push(h));return m};a.prototype.getNativeOccupationMap=function(){for(var b=this.getVerticalCases(),c=this.getHorizontalCases(),f=Array(b),a;b--;)for(f[b]=Array(c),a=c;a--;)f[b][a]=0;return f};a.prototype.getOccupationMap=function(b){for(var c=this.getNativeOccupationMap(),f=b.length;f--;)b[f].addOccupationToMap(c);return c};a.prototype.getDistanceMap=function(b,c,f){var a=b.length,h=b[0].length,
d,e,n=f,k=f,m=c,p=c,q=!1,l=Array(a);for(d=0;d<a;d++)for(l[d]=Array(h),e=0;e<h;e++)l[d][e]=-1;for(l[f][c]=0;!q;)for(q=!0,d=n;d<=k;d++)for(e=m;e<=p;e++)0<=l[d][e]&&(c=l[d][e]+1,0<d&&(-1==l[d-1][e]||l[d-1][e]>c)&&!b[d-1][e]&&(l[d-1][e]=c,d==n&&n--,q=!1),d<a-1&&-1==l[d+1][e]&&!b[d+1][e]&&(l[d+1][e]=c,d==k&&k++,q=!1),0<e&&-1==l[d][e-1]&&!b[d][e-1]&&(l[d][e-1]=c,e==m&&m--,q=!1),e<h-1&&-1==l[d][e+1]&&!b[d][e+1]&&(l[d][e+1]=c,e==p&&p++,q=!1));return l};a.prototype.getPath=function(b,c,a,g,h){var d=[],e,n=
c,k=a,m=b[0].length,p=b.length,q=new Vec2(g,h),l=Vec2.squareDistance(new Vec2(c,a),q);g=function(c,a){e=b[a][c];n=c;k=a;l=Vec2.squareDistance(new Vec2(c,a),q)};for(h=function(c,a){return b[a][c]<e||b[a][c]==e&&Vec2.squareDistance(new Vec2(c,a),q)<l};b[a][c];)if(e=-1==b[a][c]?Number.MAX_SAFE_INTEGER:b[a][c],0<c&&-1!=b[a][c-1]&&h(c-1,a)&&g(c-1,a),c<m-1&&-1!=b[a][c+1]&&h(c+1,a)&&g(c+1,a),0<a&&-1!=b[a-1][c]&&h(c,a-1)&&g(c,a-1),a<p-1&&-1!=b[a+1][c]&&h(c,a+1)&&g(c,a+1),n!=c||k!=a)c=n,a=k,d.push(c,a);else break;
return d};a.prototype.findPath=function(a,c,f,g,h){return this.getPath(this.getDistanceMap(this.getOccupationMap(this.getBoardObjects(a)),g,h),c,f,g,h)};return a}();Game.board.Object=function(){var r=Game.objects.Object.Static,a=function(a,b,g){r.call(this,a.getCasePosition(a.getBoardRect(),b,g));this.caseX=b;this.caseY=g};classExtend(r,a);a.prototype.boardMoveSpeed=100;var t=override(a,"moveOnFrame",function(a,b){t.call(this,a,b);if(this.target){var g=Vec2.translation(this.getPosition(),this.target);if(g.isZero())this.target=null;else if(g.clampMagnitude(0,this.boardMoveSpeed*b),this.move(g),g=a.getMap(),g=g.getCaseXY(g.getBoardRect(),this.getPosition()),g.x!=
this.getCaseX()||g.y!=this.getCaseY())this.setCaseX(g.x),this.setCaseY(g.y)}});a.prototype.getCaseX=function(){return this.caseX};a.prototype.getCaseY=function(){return this.caseY};a.prototype.setCaseX=function(a){this.caseX=a;return this};a.prototype.setCaseY=function(a){this.caseY=a;return this};a.prototype.setBoardMoveSpeed=function(a){this.boardMoveSpeed=a;return this};a.prototype.getBoardMoveSpeed=function(){return this.boardMoveSpeed};a.prototype.moveToCase=function(a,b,g){this.target=a.getCasePosition(a.getBoardRect(),
b,g);return this};a.prototype.skipMovement=function(){this.target&&this.move(Vec2.translation(this.getPosition(),this.target));return this};a.prototype.isMovementFinished=function(){return!this.target};a.prototype.boardOccupationMatrix=["1"];a.prototype.addOccupationToMap=function(a){for(var b=a.length,g,h=this.boardOccupationMatrix,d=h.length,e,n=this.getCaseY()-Math.floor(d/2),k,m=0;m<d&&m+n<b;m++){g=a[m].length;e=h[m].length;k=this.getCaseX()-Math.floor(e/2);for(var p=0;p<e&&p+k<g;p++)a[m+n][p+
k]|=parseInt(h[m][p])}};a.prototype.collisionLayers=[Game.objects.Object.NO_COLLISION_LAYER];var b=override(a,"getInformations",function(){var a=b.call(this);a.push(["x: ",this.getCaseX().toString(),", y: ",this.getCaseY().toString()].join(""));return a});return a}();
