/**
 * author : Loic France
 * created 05/31/2016
 */
'use strict';var Utils={merge:function(a,b,c){c=void 0===c?!1:c;for(var d in b)if(c||!a.hasOwnProperty(d))a[d]=b[d]},globalize:function(a){for(var b in a)window.hasOwnProperty(b)?console.error("the property "+b+" already exists in global space."):window[b]=a[b]},intersectionFilter:function(a,b){return-1!=a.indexOf(b)},exclusionFilter:function(a,b){return-1==a.indexOf(b)}};
window.classExtend||(window.classExtend=function(a,b){b.prototype=Object.create(a.prototype);b.prototype.constructor=b;b.super=a.prototype});window.override||(window.override=function(a,b,c){_super=a.prototype[b];a.prototype[b]=c;return _super});window.exists||(window.exists=function(a){return void 0!==a});window.isNull||(window.isNull=function(a){return void 0===a||null===a});window.createProperties||(window.createProperties=function(a,b,c){c||(c={});b&&Utils.merge(c,b);a&&Utils.merge(c,a);return c});
window.getStringFromUrl||(window.getStringFromUrl=function(a,b){var c=new XMLHttpRequest;c.open("GET",a);c.onreadystatechange=function(a){return b(c.responseText)};c.send()});window.TYPE_UNDEFINED="undefined";window.TYPE_OBJECT="object";window.TYPE_BOOLEAN="boolean";window.TYPE_NUMBER="number";window.TYPE_STRING="string";window.TYPE_FUNCTION="function";console.stack=function(a){console.error(Error(a).stack)};console.deprecated=function(a){console.stack("deprecated : "+a)};
console.map=function(a,b){b=void 0===b?"":b;for(var c=0;c<a.length;c++)a[c].join?console.log(a[c].join(b)):console.log(a[c])};var KEY={State:{UP:0,DOWN:1},BACK_SPACE:8,TAB:9,ENTER:13,MAJ:16,CTRL:17,ALT:18,VERR_MAJ:20,ESCAPE:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,BEGINNING:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,PRINT_SCR:44,INSERT:45,SUPPR:46,ZERO:48,ONE:49,TWO:50,THREE:51,FOUR:52,FIVE:53,SIX:54,SEVEN:55,EIGHT:56,NINE:57,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90,NUM_0:96,NUM_1:97,NUM_2:98,NUM_3:99,NUM_4:100,NUM_5:101,NUM_6:102,NUM_7:103,
NUM_8:104,NUM_9:105,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,VERR_NUM:144,FN:255},Input={};
(function(){for(var a=!1,b,c,d,f=Array(256),g=1;g<f.length;g++)f[g]=KEY.State.UP;var h=function(g){a=!0;d=[];c=function(a){f[a.keyCode]||(f[a.keyCode]=!0,d.forEach(function(b){b.onKeyDown(a.keyCode)&&a.preventDefault()}))};b=function(a){f[a.keyCode]&&(f[a.keyCode]=!1,d.forEach(function(b){b.onKeyUp(a.keyCode)&&e.preventDefault()}))};document.addEventListener("keydown",c,!1);document.addEventListener("keyup",b,!1)},l=function(a){!a.which&&e.button&&(a.button&1&&(a.which=1),a.button&4&&(a.which=2),
a.button&2&&(a.which=3))},k=function(a,b){return new Vec2(b.pageX-a.offsetLeft,b.pageY-a.offsetTop)};Input.KeyState={UP:0,DOWN:0};Input.addKeyListener=function(b){a||h();d.push(b)};Input.removeKeyListener=function(b){a&&d.remove(b)};Input.getKeyState=function(a){return f[a]};Input.addFocusListener=function(a,b){a.onfocus=function(){b(!0)};a.onblur=function(){b(!1)}};Input.removeFocusListener=function(a){delete a.onfocus;delete a.onblur};Input.MOUSE_UP=0;Input.MOUSE_DOWN=1;Input.MOUSE_CLICK=2;Input.MOUSE_DBCLICK=
3;Input.MOUSE_CONTEXT_MENU=4;Input.addMouseBtnListener=function(a,b){a.onclick=function(c){b.onClick&&(l(c),b.onClick(c.which,k(a,c)))};a.onmousedown=function(c){b.onMouseDown&&(l(c),b.onMouseDown(c.which,k(a,c)))};a.onmouseup=function(c){b.onMouseUp&&(l(c),b.onMouseUp(c.which,k(a,c)))};a.onrightclick=function(c){if(b.onContextMenu)return l(c),b.onContextMenu(k(a,c))};a.ondbclick=function(c){b.onDoubleClick&&(l(c),b.onDoubleClick(c.which,k(a,c)))}};Input.removeMouseBtnListener=function(a){delete a.onclick;
delete a.onmousedown;delete a.onmouseup;delete a.onrightclick;delete a.ondbclick};Input.MOUSE_EXIT=5;Input.MOUSE_ENTER=6;Input.MOUSE_MOVE=7;Input.addMouseMoveListener=function(a,b){a.onmousemove=function(c){if(b.onMouseMove)b.onMouseMove(k(a,c))};a.onmouseover=function(c){if(b.onMouseEnter)b.onMouseEnter(k(a,c))};a.onmouseout=function(c){if(b.onMouseExit)b.onMouseExit(k(a,c))}};Input.removeMouseMoveListener=function(a){delete a.onmousemove;delete a.onmouseover;delete a.onmouseout};Input.pointerLock=
function(a,b){isNull(b)||(isNull(b.pointerLockChange)||(document.addEventListener("pointerlockchange",b.pointerLockChange,!1),document.addEventListener("mozpointerlockchange",b.pointerLockChange,!1),document.addEventListener("webkitpointerlockchange",b.pointerLockChange,!1)),isNull(b.pointerLockError)||(document.addEventListener("pointerlockerror",b.pointerLockError,!1),document.addEventListener("mozpointerlockerror",b.pointerLockError,!1),document.addEventListener("webkitpointerlockerror",b.pointerLockError,
!1)));if(document.webkitFullscreenElement===elem||document.mozFullscreenElement===elem||document.mozFullScreenElement===elem)elem.requestPointerLock=elem.requestPointerLock||elem.mozRequestPointerLock||elem.webkitRequestPointerLock,elem.requestPointerLock()};Input.fullScreen=function(a,b){elem.requestFullscreen=elem.requestFullscreen||elem.mozRequestFullscreen||elem.mozRequestFullScreen||elem.webkitRequestFullscreen;elem.requestFullscreen();isNull(b)||isNull(b.fullScreenChange)||(document.addEventListener("fullscreenchange",
b.fullscreenChange,!1),document.addEventListener("mozfullscreenchange",b.fullscreenChange,!1),document.addEventListener("webkitfullscreenchange",b.fullscreenChange,!1))}})();
var KeyMap=function(){var a=this,b=[],c=[],d=[],f={onKeyDown:function(b){b=a.getAction(b);var c=!1;if(b)for(var f=d.length,k,m=0;m<f;m++)k=d[m].onDown(b),!c&&k&&(c=!0);return c},onKeyUp:function(b){b=a.getAction(b);var c=!1;if(b)for(var f=d.length,k,m=0;m<f;m++)k=d[m].onUp(b),!c&&k&&(c=!0);return c}};this.setAction=function(a,d){if(a.length)for(var f=0;f<a.length;f++)this.setAction(a[f],d);else f=b.indexOf(a),-1!==f?null===d?b.splice(f,1):c[f]=d:null!==d&&(b.push(a),c.push(d))};this.getAction=function(a){a=
b.indexOf(a);if(-1!=a)return c[a]};this.getKeyState=function(a){a=this.getKeys(a);for(var b=0;b<a.length;b++)if(Input.getKeyState(a[b]))return!0;return!1};this.getKeys=function(a){for(var d=c.indexOf(a),f=[];-1!=d;)f.push(b[d]),d=c.indexOf(a,d+1);return f};this.addListener=function(a){d.push(a);1==d.length&&Input.addKeyListener(f)};this.removeListener=function(a){a=d.indexOf(a);-1!=a&&d.splice(a,1);0===d.length&&Input.removeKeyListener(f)}};var Gravity={LEFT:1,TOP:2,RIGHT:4,BOTTOM:8,CENTER:16,getRect:function(a,b,c,d,f,g){exists(f)?exists(g)||(console.deprecated("Gravity.getRect(g,r,w,h,m)"),g=f):(console.deprecated("Gravity.getRect(g,r,w,h)"),f=g=0);b=b.copy().addMarginsXY(-f,-g);a&Gravity.CENTER||(a?(a&Gravity.LEFT||a&Gravity.RIGHT||(a|=Gravity.LEFT),!(a&Gravity.TOP)&&a&Gravity.BOTTOM&&(a|=Gravity.TOP)):a=Gravity.LEFT|Gravity.TOP);var h=g=f=NaN,l=NaN;a&Gravity.CENTER&&(f=b.left+(b.width()-c)/2,g=b.top+(b.height()-d)/2,h=b.right-(b.width()-
c)/2,l=b.bottom-(b.height()-d)/2);a&0!==Gravity.LEFT&&(f=b.left);a&0!==Gravity.TOP&&(g=b.top);a&0!==Gravity.RIGHT&&(h=b.right);a&0!==Gravity.BOTTOM&&(l=b.right);isNaN(f)?f=h-c:isNaN(h)&&(h=f+c);isNaN(g)?g=l-d:isNaN(l)&&(l=g+d);return new Rect(f,g,h,l)},getHorizontalGravity:function(a,b){b=void 0===b?null:b;return a&Gravity.LEFT?Gravity.LEFT:a&Gravity.RIGHT?Gravity.RIGHT:a&Gravity.CENTER?Gravity.CENTER:b?b:Gravity.LEFT},getVerticalGravity:function(a,b){b=void 0===b?null:b;return a&Gravity.TOP?Gravity.TOP:
a&Gravity.BOTTOM?Gravity.BOTTOM:a&Gravity.CENTER?Gravity.CENTER:b?b:Gravity.TOP}};
CanvasRenderingContext2D.prototype.wrapText||(CanvasRenderingContext2D.prototype.wrapText=function(a,b,c,d,f,g){f=void 0===f?!0:f;g=void 0===g?!1:g;var h=a.split("\n"),l=h.length;a=[];for(var k,m=[],p,t,r,q,v=b.width(),n,u=0;u<l;u++)if(t=h[u].split(" "),r=t.length){k=t[0];for(n=1;n<r;n++)p=k+" "+t[n],q=this.measureText(p),q=q.width,q>v&&0<n?(p=b.left,d&Gravity.LEFT||(d&Gravity.RIGHT?p+=this.measureText(k).width-q:d&Gravity.CENTER&&(p+=(this.measureText(k).width-q)/2)),a.push(k),k=t[n],m.push(p)):
k=p;p=b.left;d&Gravity.LEFT||(q=this.measureText(k),q=q.width,d&Gravity.RIGHT?p+=v-q:d&Gravity.CENTER&&(p+=(v-q)/2));a.push(k);m.push(p)}else a.push(h[u]),m.push(0);r=a.length;h=b.top+c;d&Gravity.TOP||(d&Gravity.BOTTOM?h=b.bottom-c*(r-1):d&Gravity.CENTER&&(h+=(b.height()-c*r)/2));for(n=0;n<r;n++)f&&this.fillText(a[n],m[n],h),g&&this.strokeText(a[n],m[n],h),h+=c});var Vec2=function(a,b){this.x=a;this.y=b};Vec2.prototype.clone=function(){return new Vec2(this.x,this.y)};Vec2.prototype.setXY=function(a,b){this.x=a;this.y=b;return this};Vec2.prototype.raz=function(){this.x=this.y=0;return this};Vec2.prototype.set=function(a){this.x=a.x;this.y=a.y;return this};Vec2.prototype.addXY=function(a,b){this.x+=a;this.y+=b;return this};Vec2.prototype.add=function(a){this.x+=a.x;this.y+=a.y;return this};Vec2.prototype.remove=function(a){this.x-=a.x;this.y-=a.y;return this};
Vec2.prototype.mul=function(a){this.x*=a;this.y*=a;return this};Vec2.prototype.squareMagnitude=function(){return this.x*this.x+this.y*this.y};Vec2.prototype.magnitude=function(){return Math.sqrt(this.squareMagnitude())};Vec2.prototype.getAngle=function(){return Math.atan2(this.y,this.x)};Vec2.prototype.rotate=function(a){a=this.getAngle()+a;var b=this.magnitude();this.setXY(b*Math.cos(a),b*Math.sin(a));return this};
Vec2.prototype.rotateAround=function(a,b){var c=Vec2.translation(a,this);c.rotate(b);this.set(c.add(a));return this};Vec2.prototype.toString=function(){return"("+this.x+", "+this.y+")"};Vec2.prototype.equalsXY=function(a,b){return this.x==a&&this.y==b};Vec2.prototype.equals=function(a){return this.x===a.x&&this.y===a.y};Vec2.prototype.isZero=function(){return!(this.x||this.y)};Vec2.prototype.getUnit=function(){return this.clone().normalize()};
Vec2.prototype.getMirror=function(a){return Vec2.translation(this,a).add(a)};Vec2.prototype.getHorizontalMirror=function(a){var b=this.clone();b.x=a?2*a-b.x:-b.x;return b};Vec2.prototype.getVerticalMirror=function(a){var b=this.clone();b.y=a?2*a-b.y:-b.y;return b};Vec2.prototype.normalize=function(){return this.mul(1/this.magnitude())};Vec2.prototype.roundedX=function(a){return a?this.x.toPrecision(a):Math.round(this.x)};Vec2.prototype.roundedY=function(a){return a?this.y.toPrecision(a):Math.round(this.y)};
Vec2.prototype.roundedVec=function(a){return new Vec2(this.roundedX(a),this.roundedY(a))};Vec2.prototype.clampMagnitude=function(a,b){var c=this.magnitude();c<a?this.mul(a/c):c>b&&this.mul(b/c);return this};Vec2.dotProd=function(a,b){return a.x*b.x+a.y*b.y};Vec2.vectProd=function(a,b){return a.x*b.y-a.y*b.u};Vec2.translation=function(a,b){return new Vec2(b.x-a.x,b.y-a.y)};Vec2.squareDistance=function(a,b){var c=b.x-a.x;a=b.y-a.y;return c*c+a*a};
Vec2.distance=function(a,b){return Math.sqrt(Vec2.squareDistance(a,b))};Vec2.ccw=function(a,b,c){return(c.y-a.y)*(b.x-a.x)>(b.y-a.y)*(c.x-a.x)};Vec2.ccw2=function(a,b){return b.y*a.x>a.y*b.x};Vec2.getRadiansBetween=function(a,b){return b.getAngle()-a.getAngle()};Vec2.createFromRadians=function(a){return new Vec2(Math.cos(a),Math.sin(a))};Vec2.copy=function(a){return new Vec2(a.x,a.y)};Vec2.zero=function(){return new Vec2(0,0)};
Vec2.createVec2Array=function(a){for(var b=Math.floor(a.length/2),c=Array(b),d;b--;)d=2*b,c[b]=new Vec2(a[d],a[d+1]);return c};Vec2.ZERO=Vec2.zero();var Rect=function(a,b,c,d){this.left=a;this.right=c;this.top=b;this.bottom=d};Rect.prototype.clone=function(){return new Rect(this.left,this.top,this.right,this.bottom)};Rect.prototype.center=function(){return(new Vec2(this.left+this.right,this.top+this.bottom)).mul(.5)};
Rect.prototype.overlap=function(a){return a.left<=this.right&&a.top<=this.bottom&&a.right>=this.left&&a.bottom>=this.top};Rect.prototype.containsXY=function(a,b){return a>=this.left&&a<=this.right&&b>=this.top&&b<=this.bottom};Rect.prototype.containsRect=function(a){return a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom};Rect.prototype.contains=function(a){return a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};
Rect.prototype.onLeftOfXY=function(a,b){return this.right<a};Rect.prototype.onLeftOfRect=function(a){return this.right<a.left};Rect.prototype.onLeftOf=function(a){return this.right<a.x};Rect.prototype.onRightOfXY=function(a,b){return this.left>a};Rect.prototype.onRightOfRect=function(a){return this.left>a.right};Rect.prototype.onRightOf=function(a){return this.left>a.x};Rect.prototype.aboveXY=function(a,b){return this.bottom<b};Rect.prototype.aboveRect=function(a){return this.bottom<a.top};
Rect.prototype.above=function(a){return this.bottom<a.y};Rect.prototype.belowXY=function(a,b){return this.top>b};Rect.prototype.belowRect=function(a){return this.top>a.bottom};Rect.prototype.below=function(a){return this.top>a.y};Rect.prototype.addMargin=function(a){this.left-=a;this.right+=a;this.top-=a;this.bottom+=a;return this};Rect.prototype.addMarginsXY=function(a,b){this.left-=a;this.right+=a;this.top-=b;this.bottom+=b;return this};
Rect.prototype.addMargins=function(a,b,c,d){this.left-=a;this.right+=c;this.top-=b;this.bottom+=d;return this};Rect.prototype.pushPath=function(a){a.rect(this.left,this.top,this.width(),this.height())};Rect.prototype.draw=function(a,b,c){a.beginPath();this.pushPath(a);a.closePath();b&&a.fill();c&&a.stroke()};Rect.prototype.setRect=function(a){this.left=a.left;this.right=a.right;this.top=a.top;this.bottom=a.bottom;return this};
Rect.prototype.set=function(a,b,c,d){this.top=b;this.left=a;this.right=c;this.bottom=d;return this};Rect.prototype.moveXY=function(a,b){this.left+=a;this.right+=a;this.top+=b;this.bottom+=b};Rect.prototype.move=function(a){this.left+=a.x;this.right+=a.x;this.top+=a.y;this.bottom+=a.y;return this};Rect.prototype.width=function(){return this.right-this.left};Rect.prototype.height=function(){return this.bottom-this.top};Rect.prototype.ratio=function(){return this.width()/this.height()};
Rect.prototype.perimeter=function(){return 2*this.width()+2*this.height()};Rect.prototype.area=function(){return this.width()*this.height()};Rect.prototype.getCurvePercentPoint=function(a){return.25>(a%=1)?new Vec2(this.left+4*a*this.width(),this.top):.5>a?new Vec2(this.right,this.top+(4*a-1)*this.height()):.75>a?new Vec2(this.right-(4*a-2)*this.width(),this.bottom):new Vec2(this.left,this.bottom-(4*a-3)*this.height())};
Rect.prototype.getShape=function(){return new Polygon(Vec2.createVec2Array([this.left,this.top,this.right,this.top,this.right,this.bottom,this.left,this.bottom]))};Rect.prototype.toString=function(){return"["+this.left+", "+this.top+", "+this.right+", "+this.bottom+"]"};Rect.getUnion=function(a){var b=a.length;if(b){for(var c=a[--b].clone();b--;)c.left=Math.min(c.left,a[b].left),c.top=Math.min(c.top,a[b].top),c.right=Math.max(c.right,a[b].right),c.bottom=Math.max(c.bottom,a[b].bottom);return c}return Rect.createEmpty()};
Rect.getIntersection=function(a){var b,c,d,f,g=a.length,h;if(g){for(;g--;)h=a[g],h.top>c&&(c=h.top),h.left>b&&(b=h.left),h.right<d&&(d=h.right),h.bottom<f&&(f=h.bottom);if(b<d&&c<f)return new Rect(b,c,d,f)}return null};Rect.createEmpty=function(a){return new Rect(0,0,0,0)};Rect.copy=function(a){return new Rect(a.left,a.top,a.right,a.bottom)};Rect.createFromPoint=function(a){return new Rect(a.x,a.y,a.x,a.y)};Rect.createFromXY=function(a,b){return new Rect(a,b,a,b)};
var Shape=function(a){this.center=a.clone()};Shape.prototype.mirrorVertically=function(a){this.center.set(this.center.getVerticalMirror(a));return this};Shape.prototype.mirrorHorizontally=function(a){this.center.set(this.center.getHorizontalMirror(a));return this};Shape.prototype.grow=function(a){return this};Shape.prototype.growDistance=function(a){return this};Shape.prototype.rotate=function(a){return this};Shape.prototype.pushPath=function(a){};Shape.prototype.getCenter=function(){return this.center};
Shape.prototype.copyCenter=function(){return this.center.clone()};Shape.prototype.intersect=function(a){return!1};Shape.prototype.contains=function(a){return!1};Shape.prototype.getRect=function(){return Rect.createFromPoint(this.center)};Shape.prototype.getCurvePercentPoint=function(a){return this.center};Shape.prototype.getRadius=function(){return 0};Shape.prototype.perimeter=function(){return 0};Shape.prototype.area=function(){return 0};Shape.prototype.clone=function(){return new Shape(this.center)};
Shape.prototype.getCircle=function(){return new Circle(this.center,this.getRadius())};Shape.prototype.moveXY=function(a,b){this.center.addXY(a,b);return this};Shape.prototype.move=function(a){this.center.add(a);return this};Shape.prototype.moveToXY=function(a,b){this.center.setXY(a,b);return this};Shape.prototype.moveTo=function(a){this.center.set(a);return this};Shape.prototype.draw=function(a,b,c){a.beginPath();this.pushPath(a);b&&a.fill();c&&a.stroke()};
var Circle=function(a,b){Shape.call(this,a);this.radius=b};classExtend(Shape,Circle);Circle.prototype.grow=function(a){this.radius*=a;return this};Circle.prototype.growDistance=function(a){this.radius+=a};Circle.prototype.pushPath=function(a){a.arc(this.center.x,this.center.y,this.radius,0,2*Math.PI,!1)};Circle.prototype.intersect=function(a){if(a instanceof Circle){var b=Vec2.distance(this.center,a.center);return b<this.radius+a.radius&&this.radius<b+a.radius&&a.radius<b+this.radius}return a.intersect(this)};
Circle.prototype.contains=function(a){return Vec2.distance(this.center,a)<this.radius};Circle.prototype.getRect=function(){return new Rect(this.center.x-this.radius,this.center.y-this.radius,this.center.x+this.radius,this.center.y+this.radius)};Circle.prototype.getCurvePercentPoint=function(a){return Vec2.createFromRadians(a*Math.PI*2).mul(this.radius).add(this.center)};Circle.prototype.getRadius=function(){return this.radius};Circle.prototype.getCircle=function(){return new Circle(this.center,this.radius)};
Circle.prototype.perimeter=function(){return 2*Math.PI*this.radius};Circle.prototype.area=function(){return Math.pow(this.radius,2)*Math.PI};Circle.prototype.clone=Circle.prototype.getCircle;var Line=function(a,b){Shape.call(this,a.clone().add(b).mul(.5));a=Vec2.translation(a,b);this.radians=a.getAngle();this.length=a.magnitude()};classExtend(Shape,Line);Line.prototype.grow=function(a){this.length*=a;return this};Line.prototype.growDistance=function(a){this.length+=2*a};
Line.prototype.rotate=function(a){this.radians+=a;return this};Line.prototype.mirrorVertically=function(a){Line.super.mirrorVertically.call(this,a);this.radians=-this.radians;return this};Line.prototype.mirrorHorizontally=function(a){Line.super.mirrorHorizontally.call(this,a);this.radians=Math.PI-this.radians;return this};
Line.prototype.pushPath=function(a){var b=this.length*Math.cos(this.radians)/2,c=this.length*Math.sin(this.radians)/2;a.moveTo(this.center.x-b,this.center.y-c);a.lineTo(this.center.x+b,this.center.y+c)};Line.prototype.getP0=function(){return this.center.clone().addXY(-(this.length*Math.cos(this.radians))/2,-(this.length*Math.sin(this.radians))/2)};Line.prototype.getP1=function(){return this.center.clone().addXY(this.length*Math.cos(this.radians)/2,this.length*Math.sin(this.radians)/2)};
Line.prototype.setP0=function(a){var b=Vec2.translation(a,this.getP1());this.radians=b.getAngle();this.length=b.magnitude();this.center.set(b.mul(.5).add(a));return this};Line.prototype.setP1=function(a){var b=this.getP0();a=Vec2.translation(b,a);this.radians=a.getAngle();this.length=a.magnitude();this.center.set(a.mul(.5).add(b));return this};Line.prototype.setPoints=function(a,b){b=Vec2.translation(a,b);this.radians=b.getAngle();this.length=b.magnitude();this.center.set(b.mul(.5).add(a));return this};
Line.prototype.getVect=function(){return new Vec2(this.length*Math.cos(this.radians),this.length*Math.sin(this.radians))};Line.prototype.getDirectorVect=function(){return Vec2.createFromRadians(this.radians)};
Line.prototype.intersect=function(a){if(a instanceof Circle){var b=this.getP0(),c=this.getP1();if(a.contains(b))return!a.contains(c);if(a.contains(c))return!a.contains(b);Vec2.translation(b,c);var d=Vec2.translation(b,a.center),f=this.getDirectorVect(),d=f.clone().mul(Vec2.dotProd(f,d)).add(b);return d.x>Math.min(b.x,c.x)&&d.x<Math.max(b.x,c.x)&&d.y>Math.min(b.y,c.y)&&d.y<Math.max(b.y,c.y)&&Vec2.distance(d,a.center)<=a.radius}if(a instanceof Line){c=this.getP0();d=this.getP1();b=a.getP0();a=a.getP1();
var f=Vec2.translation(c,b),g=Vec2.translation(d,b),h=Vec2.translation(c,a),l=Vec2.translation(d,a);return Vec2.ccw2(f,h)!=Vec2.ccw2(g,l)?(c=Vec2.translation(c,d),Vec2.translation(b,a),Vec2.ccw2(c,f)!=Vec2.ccw2(c,h)):!1}a.intersect(this)};Line.prototype.contains=function(a){var b=Vec2.translation(this.center,a),c=this.getDirectorVect();return b.equals(c.mul(Vec2.distance(this.center,a)))||b.equals(c.mul(-1))};
Line.prototype.getRect=function(){var a=this.getP1(),b=this.getP0(),c,d,f;b.x<a.x?(c=b.x,f=a.x):(c=a.x,f=b.x);b.y<a.y?(d=b.y,a=a.y):(d=a.y,a=b.y);return new Rect(c,d,f,a)};Line.prototype.getCurvePercentPoint=function(a){return this.getP0().mul(a).add(this.getP1().mul(1-a))};Line.prototype.getRadius=function(){return this.length/2};Line.prototype.perimeter=function(){return 2*this.length};Line.prototype.clone=function(){return new Line(this.getP0(),this.getP1())};
var Point=function(a){Shape.call(this,a)};classExtend(Shape,Point);Point.prototype.pushPath=function(a){a.rect(this.center.x,this.center.y,1,1)};Point.prototype.intersect=function(a){return a instanceof Circle?Vec2.distance(a.center,this.center)===a.radius:a instanceof Line?a.contains(this.center):a instanceof Point?a.center.equals(this.center):a.intersect(this)};Point.prototype.contains=function(a){return this.center.equals(a)};Point.prototype.clone=function(){return new Point(this.center)};
var Path=function(a){var b=Vec2.zero();this.points=[];if(a){var c=a.length,d=c;if(0<c){for(;d--;)b.add(a[d]);b.mul(1/c);for(d=0;d<c;d++)this.points.push(a[d].clone().remove(b))}else if(void 0===c&&(a=arguments,c=a.length,0<c)){for(d=c;d--;)b.add(a[d]);b.mul(1/c);for(d=0;d<c;d++)this.points.push(a[d].clone().remove(b))}}Shape.call(this,b);isNaN(this.center.x)&&console.stack(b)};classExtend(Shape,Path);Path.prototype.closed=!1;
Path.prototype.grow=function(a){var b=this.points.length;if(0<b)for(;b--;)this.points[b].mul(a);return this};Path.prototype.growDistance=function(a){var b,c,d=this.points.length;if(0<d)for(;d--;)c=this.points[d],b=c.magnitude(),c.mul(1/b).mul(b+a);return this};Path.prototype.rotate=function(a){var b,c=this.points.length;if(0<c)for(;c--;)b=this.points[c],b.rotate(a);return this};
Path.prototype.mirrorVertically=function(a){Path.super.mirrorVertically.call(this,a);var b=this.points.length;if(0<b)for(;b--;)a=this.points[b],a.set(a.getVerticalMirror());return this};Path.prototype.mirrorHorizontally=function(a){Path.super.mirrorHorizontally.call(this,a);var b=this.points.length;if(0<b)for(;b--;)a=this.points[b],a.set(a.getHorizontalMirror());return this};
Path.prototype.pushPath=function(a){var b=this.points.length;if(b){a.translate(this.center.x,this.center.y);a.moveTo(this.points[0].x,this.points[0].y);for(var c=1;c<b;c++)a.lineTo(this.points[c].x,this.points[c].y);this.closed&&a.closePath();a.translate(-this.center.x,-this.center.y)}};
Path.prototype.getLines=function(){for(var a=[],b=this.points.length-1,c=0;c<b;c++)a.push((new Line(this.points[c],this.points[c+1])).move(this.center));this.closed&&a.push((new Line(this.points[b],this.points[0])).move(this.center));return a};Path.prototype.intersect=function(a){var b=this.getLines(),c=b.length;if(!c)return!1;if(a instanceof Path){a=a.getLines();for(var d=a.length,f,g;c--;)for(f=b[c],g=d;g--;)if(a[g].intersect(f))return!0}else for(;c--;)if(b[c].intersect(a))return!0;return!1};
Path.prototype.getIntersectionLine=function(a){var b=this.getLines(),c=b.length,d=!1;if(!c)return null;if(a instanceof Path){a=a.getLines();for(var f=a.length,g,h;c--;)for(g=b[c],h=f;h--;)if(a[h].intersect(g))return g}else for(;c--;)if(b[c].intersect(a)){d=b[c];break}return d};
Path.prototype.contains=function(a){var b=this.getRect(),c=b.width()+10,b=b.height()+10,d=a.clone();a=[new Line(a,d.add(c,0)),new Line(a,d.add(-2*c,0)),new Line(a,d.add(c,b)),new Line(a,d.add(0,-2*b))];return this.intersect(a[0])&&this.intersect(a[1])&&this.intersect(a[2])&&this.intersect(a[3])};Path.prototype.getRect=function(){for(var a=0,b=0,c=0,d=0,f,g=this.points.length-1;0<=g;g--)f=this.points[g],f.x<a?a=f.x:f.x>c&&(c=f.x),f.y<b?b=f.y:f.y>d&&(d=f.y);a=new Rect(a,b,c,d);a.move(this.center);return a};
Path.prototype.getCurvePercentPoint=function(a){a*=this.perimeter();for(var b=this.getLines(),c=b.length,d,f=0;f<c;f++){d=b[f].length;if(d>a)return b[f].getCurvePercentPoint(a/d);a-=d}return this.points[f].add(this.center)};Path.prototype.getRadius=function(){for(var a=0,b,c=this.points.length-1;0<=c;c--)b=this.points[c].squareMagnitude(),b>a&&(a=b);return Math.sqrt(a)};
Path.prototype.redefineCenter=function(a){var b=this.points.length;if(b)if(a)for(;b--;)this.points[b].remove(a);else{a=Vec2.zero();for(var c=b;b--;)a.add(this.points[b]);a.mul(1/c);this.center.set(a)}};Path.prototype.perimeter=function(){for(var a=this.points.length-1,b=this.closed?Vec2.distance(this.points[a],this.points[0]):0;a;)b+=Vec2.distance(this.points[a--],this.points[a]);return b};
Path.prototype.area=function(){for(var a=0,b=this.points.length,c,d=this.points[0];b--;)c=this.points[b],a+=(c.x+d.x)*(c.y-d.y),d=c;return a/2};Path.prototype.clone=function(){var a=new Path([]);a.center.set(this.center);for(var b=this.points.length,c=Array(b);b--;)c[b]=this.points[b].clone();a.points=c;this.closed&&!a.closed&&(a.closed=!0);return a};var Polygon=function(a){Path.call(this,a)};classExtend(Path,Polygon);Polygon.prototype.closed=!0;
Polygon.createRectangle=function(a,b,c){var d=a.x-b/2;a=a.y-c/2;return new Polygon([{x:d,y:a},{x:d+b,y:a},{x:d+b,y:a+c},{x:d,y:a+c}])};Polygon.createFromCenter=function(a,b){var c=new Polygon([]);c.moveTo(a);a=b.length;for(c.pointsArray=Array(a);a--;)c.pointsArray[a]=b[a].clone();return c};
var RegularPolygon=function(a,b,c,d){var f=2*Math.PI/c;this.center=a.clone();this.points=Array(c);a=b.length;if(exists(a))for(var g=-1;g++<c;)this.points[g]=Vec2.createFromRadians(d).mul(b[g%a]),d+=f;else for(;c--;)this.points[c]=Vec2.createFromRadians(d).mul(b),d+=f};classExtend(Polygon,RegularPolygon);var Ray=function(a,b){Shape.call(this,a);this.radians=b};classExtend(Shape,Ray);Ray.prototype.rotate=function(a){this.radians+=a;return this};
Ray.prototype.mirrorVertically=function(a){Ray.super.mirrorVertically.call(this,a);this.radians=-this.radians;return this};Ray.prototype.mirrorHorizontally=function(a){Ray.super.mirrorHorizontally.call(this,a);this.radians=Math.PI-this.radians};Ray.prototype.endPoint=function(a){var b=this.center.clone();b.add(Math.cos(this.radians)*a,Math.sin(this.radians)*a);return b};
Ray.prototype.pushPath=function(a){var b=this.endPoint(a.canvas.clientWidth+a.canvas.clientHeight);a.moveTo(this.center.x,this.center.y);a.lineTo(b.x,b.y)};Ray.prototype.intersect=function(a){var b=a.getRect();return(new Line(this.center,this.endPoint(Vec2.distance(this.center,a.center)+b.width()+b.height()))).intersect(a)};Ray.prototype.contains=function(a){return(new Line(this.center,this.endPoint(Vec2.distance(this.center,a)))).contains(a)};
Ray.prototype.getRect=function(){var a=this.endPoint(Number.MAX_SAFE_INTEGER);return new Rect(Math.min(a.x,this.center.x),Math.min(a.y,this.center.y),Math.max(a.x,this.center.x),Math.max(a.y,this.center.y))};Ray.prototype.getRadius=function(){return Number.MAX_SAFE_INTEGER};Ray.prototype.perimeter=function(){return Number.MAX_SAFE_INTEGER};Ray.prototype.clone=function(){return new Ray(this.center,this.radians)};
